# -*- coding: utf-8 -*-
"""
Created on Tue Mar 30 13:20:59 2021

@author: Christopher.Willacy
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

#----------------------------------------------------------------------
#  GEOMETRY PAGE
#----------------------------------------------------------------------
def PageNoise(self,Wizard,icons,tipstyle,groupstyle,labelstyle):   

    self.wizardPage5 = QtWidgets.QWizardPage()
    self.wizardPage5.setObjectName("wizardPage5")      
    self.wizardPage5.setTitle("Post-Modelling Wavelet & Noise Model")
    self.verticalLayout_5b = QtWidgets.QGridLayout(self.wizardPage5)
    self.verticalLayout_5b.setObjectName("verticalLayout_5b")   
    
    self.groupBox_wavelet = QtWidgets.QGroupBox(self.wizardPage5)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_wavelet.setFont(font)
    self.groupBox_wavelet.setStyleSheet(groupstyle)
    self.groupBox_wavelet.setObjectName("groupBox_wavelet")
    self.groupBox_wavelet.setTitle('Wavelet Convolution')
    self.verticalLayout_wavelet = QtWidgets.QVBoxLayout(self.groupBox_wavelet)
    self.verticalLayout_wavelet.setObjectName("verticalLayout_wavelet")
    self.horizontalLayout_wavelet = QtWidgets.QHBoxLayout()
    self.horizontalLayout_wavelet.setObjectName("horizontalLayout_wavelet")
    self.label_wavelet = QtWidgets.QLabel(self.groupBox_wavelet)
    self.label_wavelet.setObjectName("label_wavelet")
    self.label_wavelet.setStyleSheet(labelstyle)
    self.label_wavelet.setText("Convolve data with a wavelet?:")
    self.horizontalLayout_wavelet.addWidget(self.label_wavelet)
    self.checkBox_wavelet = QtWidgets.QCheckBox(self.groupBox_wavelet)
    self.checkBox_wavelet.setText("")
    self.checkBox_wavelet.setChecked(False)
    self.checkBox.setObjectName("checkBox_wavelet")            
    self.horizontalLayout_wavelet.addWidget(self.checkBox_wavelet)
    self.checkBox_wavelet.setToolTip("option to convolve the data with a wavelet")
    self.checkBox_wavelet.setStyleSheet(tipstyle)          
  
    self.verticalLayout_wavelet.addLayout(self.horizontalLayout_wavelet) 
    self.verticalLayout_5b.addWidget(self.groupBox_wavelet)      
    
    self.horizontalLayout_waveload = QtWidgets.QHBoxLayout()
    self.horizontalLayout_waveload.setObjectName("horizontalLayout_waveload")
   
    self.label_waveload = QtWidgets.QLabel(self.groupBox_wavelet)
    self.label_waveload.setBaseSize(QtCore.QSize(0, 0))
    self.label_waveload.setObjectName("label_waveload")
    self.label_waveload.setStyleSheet(labelstyle)
    self.label_waveload.setText("WAVSAM File:")
    self.horizontalLayout_waveload.addWidget(self.label_waveload)
    
    self.lineEdit_wavelet = QtWidgets.QLineEdit(self.groupBox_wavelet)
    self.lineEdit_wavelet.setObjectName("lineEdit_wavelet")
    self.horizontalLayout_waveload.addWidget(self.lineEdit_wavelet)       
    self.lineEdit_wavelet.setToolTip("enter a WAVSAM for the wavelet")
    self.lineEdit_wavelet.setStyleSheet(tipstyle)
    self.lineEdit_wavelet.setDisabled(True)
    self.lineEdit_wavelet.textChanged[str].connect(self.changestate_wavelet)    
    
    self.pushButton_wavelet = QtWidgets.QPushButton(self.groupBox_wavelet)
    self.pushButton_wavelet.setObjectName("pushButton_wavelet")
    self.pushButton_wavelet.setStyleSheet("border: none")
    self.pushButton_wavelet.setDisabled(True)
    self.pushButton_wavelet.setIcon(QIcon(icons[3])) 
    self.horizontalLayout_waveload.addWidget(self.pushButton_wavelet)
    self.verticalLayout_wavelet.addLayout(self.horizontalLayout_waveload)        
    self.pushButton_wavelet.clicked.connect(self.openFileNameDialog_wavelet)
    self.checkBox_wavelet.clicked.connect(self.changestate_checkwavelet)
            
    #----next group box----
    self.groupBox_5b = QtWidgets.QGroupBox(self.wizardPage5)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_5b.setFont(font)
    self.groupBox_5b.setStyleSheet(groupstyle)
    self.groupBox_5b.setObjectName("groupBox_5b")
    self.groupBox_5b.setTitle("SIPMAP-NOSADD")
    self.verticalLayout_6b = QtWidgets.QVBoxLayout(self.groupBox_5b)
    self.verticalLayout_6b.setObjectName("verticalLayout_5b")
    self.horizontalLayout_3b = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3b.setObjectName("horizontalLayout_3b")
    self.label_4b = QtWidgets.QLabel(self.groupBox_5b)
    self.label_4b.setObjectName("label_4b")
    self.label_4b.setStyleSheet(labelstyle)
    self.label_4b.setText("Add noise to output?:")
    self.horizontalLayout_3b.addWidget(self.label_4b)    
    #spacerItem_5b = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    #self.horizontalLayout_3b.addItem(spacerItem_5b)
    self.checkBox_5b = QtWidgets.QCheckBox(self.groupBox_5b)
    self.checkBox_5b.setText("")
    self.checkBox_5b.setChecked(False)
    self.checkBox_5b.setObjectName("checkBox_5b")        
    self.horizontalLayout_3b.addWidget(self.checkBox_5b)
    self.checkBox_5b.setToolTip("option to add random noise to output data")
    self.checkBox_5b.setStyleSheet(tipstyle)       
    self.checkBox_5b.clicked.connect(self.changestate_noise)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_3b)      
    self.horizontalLayout_4b = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4b.setObjectName("horizontalLayout_4b")      
    self.label_5b = QtWidgets.QLabel(self.groupBox_5b)
    self.label_5b.setObjectName("label_5b") 
    self.label_5b.setStyleSheet(labelstyle)
    self.label_5b.setText("Noise mode:")
    self.horizontalLayout_4b.addWidget(self.label_5b)   
    
    #-----------
    # radiobutton for pre- or post- noise
    self.horizontalLayout_3c = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3c.setObjectName("horizontalLayout_3c")
    self.label_4c = QtWidgets.QLabel(self.groupBox_5b)
    self.label_4c.setObjectName("label_4c") 
    self.label_4c.setStyleSheet(labelstyle)
    self.label_4c.setText("Add noise pre- or post-blending?:")
    self.horizontalLayout_3c.addWidget(self.label_4c)   
    spacerItem_4c = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_3c.addItem(spacerItem_4c)    
    self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_5)
    self.radioButton_1.setObjectName("radioButton_1") 
    self.radioButton_1.setText("pre")                
    self.horizontalLayout_3c.addWidget(self.radioButton_1)        
    self.radioButton_1.setToolTip("option to apply random noise on the pre- or post-blended data")
    self.radioButton_1.setStyleSheet(tipstyle)  

    self.radioButton_1.clicked.connect(self.changestate_noisepre)    
    self.radioButton_1.setChecked(True)
    self.radioButton_1.setDisabled(True) 
            
    self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
    self.radioButton_2.setObjectName("radioButton_2") 
    self.radioButton_2.setText("post")                
    self.horizontalLayout_3c.addWidget(self.radioButton_2)
    self.radioButton_2.setToolTip("option to apply random noise on the pre- or post-blended data")
    self.radioButton_2.setStyleSheet(tipstyle) 
    self.radioButton_2.clicked.connect(self.changestate_noisepos)  
    self.radioButton_2.setChecked(False)
    self.radioButton_2.setDisabled(True) 
    spacerItem_2r = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_3c.addItem(spacerItem_2r)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_3c)
           
    #----------
    
    self.comboBox_3b = QtWidgets.QComboBox(self.groupBox_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
    self.comboBox_3b.setSizePolicy(sizePolicy)
    self.comboBox_3b.setCurrentText("")
    self.comboBox_3b.setObjectName("comboBox_3b")
    self.horizontalLayout_4b.addWidget(self.comboBox_3b)
    self.comboBox_3b.addItem("NDB")      
    self.comboBox_3b.addItem("SNR") 
    self.comboBox_3b.setToolTip("noise mode to be used")
    self.comboBox_3b.setStyleSheet(tipstyle)    
    self.comboBox_3b.activated[str].connect(self.changestate_noisemod)
    self.comboBox_3b.setDisabled(False)  
    spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_4b.addItem(spacerItem5)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_4b)
    
    self.horizontalLayout_5b = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5b.setObjectName("horizontalLayout_5b")
    spacerItem_6b = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5b.addItem(spacerItem_6b)       
    self.label_6b = QtWidgets.QLabel(self.groupBox_5b)
    self.label_6b.setObjectName("label_6b") 
    self.label_6b.setStyleSheet(labelstyle)
    self.label_6b.setText("faclev:")         
    self.horizontalLayout_5b.addWidget(self.label_6b)    
    self.lineEdit_faclev = QtWidgets.QLineEdit(self.groupBox_5b)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_faclev.sizePolicy().hasHeightForWidth())
    self.lineEdit_faclev.setSizePolicy(sizePolicy)
    self.lineEdit_faclev.setMaximumSize(QtCore.QSize(95, 16777215))
    self.lineEdit_faclev.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_faclev.setObjectName("lineEdit_faclev")               
    self.horizontalLayout_5b.addWidget(self.lineEdit_faclev)
    self.lineEdit_faclev.setToolTip("noise level depending on the selection of the noise mode, i.e. signal to noise ratio or fixed level.")
    self.lineEdit_faclev.setStyleSheet(tipstyle)   
    self.lineEdit_faclev.textChanged[str].connect(self.changestate_faclev) 
    self.lineEdit_faclev.setDisabled(True)
    spacerItem_faclev = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5b.addItem(spacerItem_faclev)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_5b)
    
    #----------
    self.horizontalLayout_5c = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5c.setObjectName("horizontalLayout_5c")
    spacerItem_6c = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5c.addItem(spacerItem_6c)
    self.label_6c = QtWidgets.QLabel(self.groupBox_5b)
    self.label_6c.setObjectName("label_6c") 
    self.label_6c.setStyleSheet(labelstyle)
    self.label_6c.setText("flow:")
    self.horizontalLayout_5c.addWidget(self.label_6c)    
    self.lineEdit_flow = QtWidgets.QLineEdit(self.groupBox_5b)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_flow.sizePolicy().hasHeightForWidth())
    self.lineEdit_flow.setSizePolicy(sizePolicy)
    self.lineEdit_flow.setMaximumSize(QtCore.QSize(95, 16777215))
    self.lineEdit_flow.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_flow.setObjectName("lineEdit_flow")              
    self.horizontalLayout_5c.addWidget(self.lineEdit_flow)
    self.lineEdit_flow.setToolTip("-3 dB frequency of low frequency slope (Hz).FLOW = 0: the filter will not have a low frequency slope.")
    self.lineEdit_flow.setStyleSheet(tipstyle) 
    self.lineEdit_flow.textChanged[str].connect(self.changestate_flow) 
    self.lineEdit_flow.setDisabled(True)
    spacerItem_flow = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5c.addItem(spacerItem_flow)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_5c) 
        
    self.horizontalLayout_5d = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5d.setObjectName("horizontalLayout_5d")
    spacerItem_6d = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5d.addItem(spacerItem_6d)
    self.label_6d = QtWidgets.QLabel(self.groupBox_5b)
    self.label_6d.setObjectName("label_6d")
    self.label_6d.setStyleSheet(labelstyle)
    self.label_6d.setText("iorlow:")        
    self.horizontalLayout_5d.addWidget(self.label_6d)    
    self.lineEdit_iorlow = QtWidgets.QLineEdit(self.groupBox_5b)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_iorlow.sizePolicy().hasHeightForWidth())
    self.lineEdit_iorlow.setSizePolicy(sizePolicy)
    self.lineEdit_iorlow.setMaximumSize(QtCore.QSize(95, 16777215))
    self.lineEdit_iorlow.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_iorlow.setObjectName("lineEdit_iorlow")               
    self.horizontalLayout_5d.addWidget(self.lineEdit_iorlow)
    self.lineEdit_iorlow.setToolTip("order of low frequency slope; the steepness of the slope is 6 * IORLOW dB/octave.")
    self.lineEdit_iorlow.setStyleSheet(tipstyle) 
    self.lineEdit_iorlow.textChanged[str].connect(self.changestate_iorlow) 
    self.lineEdit_iorlow.setDisabled(True)
    spacerItem_iorlow = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5d.addItem(spacerItem_iorlow)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_5d) 
    
    self.horizontalLayout_5e = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5e.setObjectName("horizontalLayout_5e")
    spacerItem_6e = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5e.addItem(spacerItem_6e)
    self.label_6e = QtWidgets.QLabel(self.groupBox_5b)
    self.label_6e.setObjectName("label_6e") 
    self.label_6e.setStyleSheet(labelstyle)
    self.label_6e.setText("fhigh:")
    self.horizontalLayout_5e.addWidget(self.label_6e)    
    self.lineEdit_fhigh = QtWidgets.QLineEdit(self.groupBox_5b)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_fhigh.sizePolicy().hasHeightForWidth())
    self.lineEdit_fhigh.setSizePolicy(sizePolicy)
    self.lineEdit_fhigh.setMaximumSize(QtCore.QSize(95, 16777215))
    self.lineEdit_fhigh.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_fhigh.setObjectName("lineEdit_fhigh")               
    self.horizontalLayout_5e.addWidget(self.lineEdit_fhigh)
    self.lineEdit_fhigh.setToolTip("-3 dB frequency of high frequency slope (Hz).FHIGH = 0: the filter will not have a high frequency slope.")
    self.lineEdit_fhigh.setStyleSheet(tipstyle) 
    self.lineEdit_fhigh.textChanged[str].connect(self.changestate_fhigh) 
    self.lineEdit_fhigh.setDisabled(True)
    spacerItem_fhigh = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5e.addItem(spacerItem_fhigh)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_5e) 
    
    self.horizontalLayout_5f = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5f.setObjectName("horizontalLayout_5f")
    spacerItem_6f = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5f.addItem(spacerItem_6f)
    self.label_6f = QtWidgets.QLabel(self.groupBox_5b)
    self.label_6f.setObjectName("label_6f") 
    self.label_6f.setStyleSheet(labelstyle)
    self.label_6f.setText("iorhig:")
    self.horizontalLayout_5f.addWidget(self.label_6f)    
    self.lineEdit_iorhig = QtWidgets.QLineEdit(self.groupBox_5b)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_iorhig.sizePolicy().hasHeightForWidth())
    self.lineEdit_iorhig.setSizePolicy(sizePolicy)
    self.lineEdit_iorhig.setMaximumSize(QtCore.QSize(95, 16777215))
    self.lineEdit_iorhig.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_iorhig.setObjectName("lineEdit_iorhig")               
    self.horizontalLayout_5f.addWidget(self.lineEdit_iorhig)
    self.lineEdit_iorhig.setToolTip("order of high frequency slope; the steepness of the slope is 6 * IORHIG dB/octave.")
    self.lineEdit_iorhig.setStyleSheet(tipstyle) 
    self.lineEdit_iorhig.textChanged[str].connect(self.changestate_iorhig) 
    self.lineEdit_iorhig.setDisabled(True)
    spacerItem_iorhig = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_5f.addItem(spacerItem_iorhig)
    self.verticalLayout_6b.addLayout(self.horizontalLayout_5f)     
    self.verticalLayout_5b.addWidget(self.groupBox_5b)   
    
    #Wizard.addPage(self.wizardPage5)
    Wizard.setPage(5,self.wizardPage5)