# -*- coding: utf-8 -*-
"""
Created on Tue Mar 30 13:29:37 2021

@author: Christopher.Willacy
"""
import platform
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

#----------------------------------------------------------------------
#   OUTPUT OPTIONS
#----------------------------------------------------------------------
def PageOutput(self,Wizard,icons,df,tipstyle,groupstyle,labelstyle,library,project): 
    
    self.wizardPage8 = QtWidgets.QWizardPage()
    self.wizardPage8.setObjectName("wizardPage8")
    self.wizardPage8.setTitle("Output Options")
    self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.wizardPage8)
    self.verticalLayout_7.setObjectName("verticalLayout_7")
    
    self.groupBox_6 = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_6.setFont(font)
    self.groupBox_6.setStyleSheet(groupstyle)
    self.groupBox_6.setObjectName("groupBox_6")
    self.groupBox_6.setTitle("JobPro Project")
    self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
    self.verticalLayout_8.setObjectName("verticalLayout_8")  
    self.horizontalLayout_jp = QtWidgets.QHBoxLayout()
    self.horizontalLayout_jp.setObjectName("horizontalLayout_jp")
    self.label_jl = QtWidgets.QLabel(self.groupBox_6)
    self.label_jl.setObjectName("label_jl")
    self.label_jl.setStyleSheet(labelstyle)
    self.label_jl.setText("JobPro Library:")       
    self.horizontalLayout_jp.addWidget(self.label_jl)

    self.comboBox_jl = QtWidgets.QComboBox(self.groupBox_6)
    self.comboBox_jl.setCurrentText("")
    self.comboBox_jl.setObjectName("comboBox_jl")
    self.comboBox_jl.setFixedWidth(250)
    self.horizontalLayout_jp.addWidget(self.comboBox_jl)
    spacerItem_jllab = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
    self.horizontalLayout_jp.addItem(spacerItem_jllab)
    
    self.comboBox_jl.addItem('')
    # add the JobPro libraries   
    for element in library:
        self.comboBox_jl.addItem(element)

    mylib = df.loc[df['PARAMETER'] == 'JPLIB', 'VALUE']
    
    self.comboBox_jl.setCurrentText('')
    #self.comboBox_jl.setCurrentText(str(mylib))
    self.comboBox_jl.setToolTip("select JobPro library")
    self.comboBox_jl.setStyleSheet(tipstyle)
    self.comboBox_jl.activated[str].connect(self.changestate_select_jpprojects)

    self.horizontalLayout_jp2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_jp2.setObjectName("horizontalLayout_jp2")
    self.label_jp = QtWidgets.QLabel(self.groupBox_6)
    self.label_jp.setObjectName("label_jl")
    self.label_jp.setStyleSheet(labelstyle)
    self.label_jp.setText("JobPro Project:")      
    self.horizontalLayout_jp2.addWidget(self.label_jp)
    spacerItem_jp = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)

    
    self.comboBox_jp = QtWidgets.QComboBox(self.groupBox_6)
    self.comboBox_jp.setObjectName("comboBox_jp")
    self.comboBox_jp.setFixedWidth(250)

    self.horizontalLayout_jp2.addWidget(self.comboBox_jp)
    self.horizontalLayout_jp2.addItem(spacerItem_jp)
        
    self.comboBox_jp.addItem('')
        
    # add the JobPro libraries   
    for element in project:
        self.comboBox_jp.addItem(element)

    self.comboBox_jp.setCurrentText('')

    self.comboBox_jp.setToolTip("select JobPro project")
    self.comboBox_jp.setStyleSheet(tipstyle)
    self.comboBox_jp.activated[str].connect(self.changestate_set_jpproject)
    
    #----------
    self.horizontalLayout_part = QtWidgets.QHBoxLayout()
    self.horizontalLayout_part.setObjectName("horizontalLayout_part")
    self.label_part = QtWidgets.QLabel(self.groupBox_6)
    self.label_part.setObjectName("label_part")
    self.label_part.setStyleSheet(labelstyle)
    self.label_part.setText("JobPro Partition:")  
    #self.label_part.setFixedWidth(200)      
    self.horizontalLayout_part.addWidget(self.label_part)
    self.lineEdit_part = QtWidgets.QLineEdit(self.groupBox_6)
    self.lineEdit_part.setObjectName("lineEdit_part")
    self.lineEdit_part.setToolTip("partition basename to be used for creating partitions")
    self.lineEdit_part.setStyleSheet(tipstyle)
    val = df.loc[63,"VALUE"]
    self.lineEdit_part.setText(str(val))
    self.lineEdit_part.setMaximumSize(QtCore.QSize(250, 16777215))
    self.lineEdit_part.setBaseSize(QtCore.QSize(0, 0))
    
    if platform.system() == 'Linux': 
        self.lineEdit_part.setDisabled(False)
    else:
        self.lineEdit_part.setDisabled(True)
    
    spacerItem_part = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.lineEdit_part.textChanged[str].connect(self.changestate_part)
    self.horizontalLayout_part.addWidget(self.lineEdit_part)
    self.horizontalLayout_part.addItem(spacerItem_part)
    #----------
        
    self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_6.setObjectName("horizontalLayout_6")
    self.label_7 = QtWidgets.QLabel(self.groupBox_6)
    self.label_7.setObjectName("label_7")
    self.label_7.setStyleSheet(labelstyle)
    self.label_7.setText("Output skl directory:")  
    self.label_7.setFixedWidth(200)      
    self.horizontalLayout_6.addWidget(self.label_7)
    self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_6)
    self.lineEdit_4.setObjectName("lineEdit_4")
    
    self.horizontalLayout_6.addWidget(self.lineEdit_4)
    self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_6)
    self.pushButton_2.setObjectName("pushButton_2")
    self.pushButton_2.setStyleSheet("border: none")
    self.pushButton_2.setIcon(QIcon(icons[3]))
    self.horizontalLayout_6.addWidget(self.pushButton_2)
    
    self.verticalLayout_8.addLayout(self.horizontalLayout_jp)
    self.verticalLayout_8.addLayout(self.horizontalLayout_jp2)
    self.verticalLayout_8.addLayout(self.horizontalLayout_part)
    self.verticalLayout_8.addLayout(self.horizontalLayout_6)
    
    
    #----------
    
    self.lineEdit_4.setToolTip("output directory where the skeletons will be written")
    self.lineEdit_4.setStyleSheet(tipstyle) 
    self.lineEdit_4.setText('')
    self.lineEdit_4.textChanged[str].connect(self.changestate_outdir)
    self.verticalLayout_7.addWidget(self.groupBox_6)
    self.groupBox_9 = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_9.setFont(font)
    self.groupBox_9.setStyleSheet(groupstyle)
    self.groupBox_9.setObjectName("groupBox_9")
    self.groupBox_9.setTitle("SSF Output")    
    self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_9)
    self.verticalLayout_11.setObjectName("verticalLayout_11")
    self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_7.setObjectName("horizontalLayout_7")
    self.label_8 = QtWidgets.QLabel(self.groupBox_9)
    self.label_8.setObjectName("label_8")
    self.label_8.setStyleSheet(labelstyle)
    self.label_8.setText("Generate SSF traces?:")       
    self.horizontalLayout_7.addWidget(self.label_8)
    self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_9)
    self.checkBox_3.setText("")
    self.checkBox_3.setChecked(True)
    self.checkBox_3.setObjectName("checkBox_3")
    self.horizontalLayout_7.addWidget(self.checkBox_3)
    self.verticalLayout_11.addLayout(self.horizontalLayout_7)
    self.checkBox_3.setToolTip("option to generate SSF traces on output (default=true)")
    self.checkBox_3.setStyleSheet(tipstyle) 
    self.checkBox_3.clicked.connect(self.changestate_ssf)
    self.verticalLayout_7.addWidget(self.groupBox_9)
      
    self.groupBox_8 = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_8.setFont(font)
    self.groupBox_8.setStyleSheet(groupstyle)
    self.groupBox_8.setObjectName("groupBox_8")
    self.groupBox_8.setTitle("QC Displays")       
    self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_8)
    self.verticalLayout_10.setObjectName("verticalLayout_10")
    self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_17.setObjectName("horizontalLayout_17")
    self.label_18 = QtWidgets.QLabel(self.groupBox_8)
    self.label_18.setObjectName("label_18")
    self.label_18.setStyleSheet(labelstyle)
    self.label_18.setText("Geometry displays?")      
    self.horizontalLayout_17.addWidget(self.label_18)
    
    self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_8)
    self.checkBox_6.setText("")
    self.checkBox_6.setChecked(False)
    self.checkBox_6.setObjectName("checkBox_6")
    self.horizontalLayout_17.addWidget(self.checkBox_6)
    self.checkBox_6.setToolTip("option to create source/receiver geometry qc images")
    self.checkBox_6.setStyleSheet(tipstyle) 
    self.checkBox_6.clicked.connect(self.changestate_qcgeom)
    self.verticalLayout_10.addLayout(self.horizontalLayout_17)
    
    self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_19.setObjectName("horizontalLayout_19")
    self.label_19 = QtWidgets.QLabel(self.groupBox_8)
    self.label_19.setObjectName("label_19")
    self.label_19.setStyleSheet(labelstyle)
    self.label_19.setText("Timing displays?")        
    self.horizontalLayout_19.addWidget(self.label_19)
    self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_8)
    self.checkBox_7.setText("")
    self.checkBox_7.setChecked(False)
    self.checkBox_7.setObjectName("checkBox_7")
    self.horizontalLayout_19.addWidget(self.checkBox_7)
    self.checkBox_7.setToolTip("option to create source timing qc images")
    self.checkBox_7.setStyleSheet(tipstyle) 
    self.checkBox_7.clicked.connect(self.changestate_qctime)
    self.verticalLayout_10.addLayout(self.horizontalLayout_19)
    
    self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_20.setObjectName("horizontalLayout_20")
    self.label_20 = QtWidgets.QLabel(self.groupBox_8)
    self.label_20.setObjectName("label_20")
    self.label_20.setStyleSheet(labelstyle)
    self.label_20.setText("Sensor depth displays?")       
    self.horizontalLayout_20.addWidget(self.label_20)
    self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_8)
    self.checkBox_8.setText("")
    self.checkBox_8.setChecked(False)
    self.checkBox_8.setObjectName("checkBox_8")
    self.horizontalLayout_20.addWidget(self.checkBox_8)
    self.checkBox_8.setToolTip("option to create sensor depth qc images")
    self.checkBox_8.setStyleSheet(tipstyle) 
    self.checkBox_8.clicked.connect(self.changestate_qcdepth)
    self.verticalLayout_10.addLayout(self.horizontalLayout_20)
    self.verticalLayout_7.addWidget(self.groupBox_8)
    
    #--------

    self.groupBox_perf = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_perf.setFont(font)
    self.groupBox_perf.setStyleSheet(groupstyle)
    self.groupBox_perf.setObjectName("groupBox_perf")
    self.groupBox_perf.setTitle("Sort Size")        
    self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_perf)
    self.verticalLayout_11.setObjectName("verticalLayout_11")
    self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_21.setObjectName("horizontalLayout_21")
    self.label_21 = QtWidgets.QLabel(self.groupBox_perf)
    self.label_21.setObjectName("label_21")
    self.label_21.setStyleSheet(labelstyle)
    self.label_21.setText("SQSORT maxrec:")       
    self.horizontalLayout_21.addWidget(self.label_21)
    
    self.lineEdit_sqsaf = QtWidgets.QLineEdit(self.groupBox_perf)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_sqsaf.setSizePolicy(sizePolicy)
    self.lineEdit_sqsaf.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_sqsaf.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_sqsaf.setObjectName("lineEdit_sqsaf")
    self.lineEdit_sqsaf.setMaxLength(7)
    val = df.loc[32,"VALUE"]
    self.lineEdit_sqsaf.setText(str(val))
    self.horizontalLayout_21.addWidget(self.lineEdit_sqsaf)
    self.lineEdit_sqsaf.setToolTip("maximum number of SAF records that need to be stored in memory expressed in millions")
    self.lineEdit_sqsaf.setStyleSheet(tipstyle) 
    self.lineEdit_sqsaf.textChanged[str].connect(self.changestate_sqsaf)
    
    spacerItem_sqsaf = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_21.addItem(spacerItem_sqsaf)
    
    self.verticalLayout_11.addLayout(self.horizontalLayout_21)
    
    self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_22.setObjectName("horizontalLayout_22")
    self.label_22 = QtWidgets.QLabel(self.groupBox_perf)
    self.label_22.setObjectName("label_22")
    self.label_22.setStyleSheet(labelstyle)
    self.label_22.setText("SRTALL maxsize:")
    self.horizontalLayout_22.addWidget(self.label_22)
    
    self.lineEdit_srtall = QtWidgets.QLineEdit(self.groupBox_perf)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_srtall.setSizePolicy(sizePolicy)
    self.lineEdit_srtall.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_srtall.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_srtall.setObjectName("lineEdit_sqsaf")
    self.lineEdit_srtall.setMaxLength(6)
    val = df.loc[33,"VALUE"]
    self.lineEdit_srtall.setText(str(val))
    self.lineEdit_srtall.setText("4000")
    self.horizontalLayout_22.addWidget(self.lineEdit_srtall)
    self.lineEdit_srtall.setToolTip("maximum size of the sort buffer in Mb's")
    self.lineEdit_srtall.setStyleSheet(tipstyle)
    self.lineEdit_srtall.textChanged[str].connect(self.changestate_srtall)
    spacerItem_srtall = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_22.addItem(spacerItem_srtall)
    
    self.verticalLayout_11.addLayout(self.horizontalLayout_22)                    
    self.verticalLayout_7.addWidget(self.groupBox_perf)

    # ---------------
    self.groupBox_range = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_range.setFont(font)
    self.groupBox_range.setStyleSheet(groupstyle)
    self.groupBox_range.setObjectName("groupBox_range")
    self.groupBox_range.setTitle("Ident Ranging for Multi-Segment Partitions")        
    self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_range)
    self.verticalLayout_12.setObjectName("verticalLayout_12")
    self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_23.setObjectName("horizontalLayout_23")
    self.label_23 = QtWidgets.QLabel(self.groupBox_range)
    self.label_23.setObjectName("label_23")
    self.label_23.setStyleSheet(labelstyle)
    self.label_23.setText("Ident1:")       
    self.horizontalLayout_23.addWidget(self.label_23)
       
    self.lineEdit_ident1 = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident1.setSizePolicy(sizePolicy)
    self.lineEdit_ident1.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident1.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident1.setObjectName("lineEdit_ident1")
    self.lineEdit_ident1.setMaxLength(6)
    val = df.loc[52,"VALUE"]
    self.lineEdit_ident1.setText(str(val))
    self.horizontalLayout_23.addWidget(self.lineEdit_ident1)
    self.lineEdit_ident1.setToolTip("primary ident to use for skeleton input ranging")
    self.lineEdit_ident1.setStyleSheet(tipstyle) 
    self.lineEdit_ident1.textChanged[str].connect(self.changestate_ident1)
      
    # ident1 minval
    self.lineEdit_ident1minval = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident1minval.setSizePolicy(sizePolicy)
    self.lineEdit_ident1minval.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident1minval.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident1minval.setObjectName("lineEdit_ident1minval")
    self.lineEdit_ident1minval.setMaxLength(8)
    val = df.loc[55,"VALUE"]
    self.lineEdit_ident1minval.setText(str(val))
    self.horizontalLayout_23.addWidget(self.lineEdit_ident1minval)
    self.lineEdit_ident1minval.setToolTip("minimum value for ident1")
    self.lineEdit_ident1minval.setStyleSheet(tipstyle) 
    self.lineEdit_ident1minval.textChanged[str].connect(self.changestate_ident1minval)
    
    # ident1 maxval
    self.lineEdit_ident1maxval = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident1maxval.setSizePolicy(sizePolicy)
    self.lineEdit_ident1maxval.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident1maxval.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident1maxval.setObjectName("lineEdit_ident1maxval")
    self.lineEdit_ident1maxval.setMaxLength(8)
    val = df.loc[56,"VALUE"]
    self.lineEdit_ident1maxval.setText(str(val))
    self.horizontalLayout_23.addWidget(self.lineEdit_ident1maxval)
    self.lineEdit_ident1maxval.setToolTip("maximum value for ident1")
    self.lineEdit_ident1maxval.setStyleSheet(tipstyle) 
    self.lineEdit_ident1maxval.textChanged[str].connect(self.changestate_ident1maxval)
    
    # ident1 inc
    self.lineEdit_ident1inc = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident1inc.setSizePolicy(sizePolicy)
    self.lineEdit_ident1inc.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident1inc.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident1inc.setObjectName("lineEdit_ident1inc")
    self.lineEdit_ident1inc.setMaxLength(8)
    val = df.loc[64,"VALUE"]
    self.lineEdit_ident1inc.setText(str(val))
    self.horizontalLayout_23.addWidget(self.lineEdit_ident1inc)
    self.lineEdit_ident1inc.setToolTip("increment value for ident1")
    self.lineEdit_ident1inc.setStyleSheet(tipstyle) 
    self.lineEdit_ident1inc.textChanged[str].connect(self.changestate_ident1inc)
    
    self.verticalLayout_12.addLayout(self.horizontalLayout_23)
    spacerItem_ident1 = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_23.addItem(spacerItem_ident1)
       
    
    self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_24.setObjectName("horizontalLayout_24")
    self.label_24 = QtWidgets.QLabel(self.groupBox_range)
    self.label_24.setObjectName("label_24")
    self.label_24.setStyleSheet(labelstyle)
    self.label_24.setText("Ident2:")       
    self.horizontalLayout_24.addWidget(self.label_24)
       
    self.lineEdit_ident2 = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident2.setSizePolicy(sizePolicy)
    self.lineEdit_ident2.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident2.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident2.setObjectName("lineEdit_ident2")
    self.lineEdit_ident2.setMaxLength(6)
    val = df.loc[53,"VALUE"]
    self.lineEdit_ident2.setText(str(val))
    self.horizontalLayout_24.addWidget(self.lineEdit_ident2)
    self.lineEdit_ident2.setToolTip("secondary ident to use for skeleton input ranging")
    self.lineEdit_ident2.setStyleSheet(tipstyle) 
    
    self.lineEdit_ident2.setDisabled(True)
    
    self.lineEdit_ident2.textChanged[str].connect(self.changestate_ident2)
    
    
    # ident2 minval
    self.lineEdit_ident2minval = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident2minval.setSizePolicy(sizePolicy)
    self.lineEdit_ident2minval.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident2minval.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident2minval.setObjectName("lineEdit_ident2minval")
    self.lineEdit_ident2minval.setMaxLength(8)
    val = df.loc[57,"VALUE"]
    self.lineEdit_ident2minval.setText(str(val))
    self.lineEdit_ident2minval.setDisabled(True)
    self.horizontalLayout_24.addWidget(self.lineEdit_ident2minval)
    self.lineEdit_ident2minval.setToolTip("minimum value for ident2")
    self.lineEdit_ident2minval.setStyleSheet(tipstyle) 
    self.lineEdit_ident2minval.textChanged[str].connect(self.changestate_ident2minval)
    
    # ident2 maxval
    self.lineEdit_ident2maxval = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident2maxval.setSizePolicy(sizePolicy)
    self.lineEdit_ident2maxval.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident2maxval.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident2maxval.setObjectName("lineEdit_ident2maxval")
    self.lineEdit_ident2maxval.setMaxLength(8)
    val = df.loc[58,"VALUE"]
    self.lineEdit_ident2maxval.setText(str(val))
    self.lineEdit_ident2maxval.setDisabled(True)
    self.horizontalLayout_24.addWidget(self.lineEdit_ident2maxval)
    self.lineEdit_ident2maxval.setToolTip("maximum value for ident2")
    self.lineEdit_ident2maxval.setStyleSheet(tipstyle) 
    self.lineEdit_ident2maxval.textChanged[str].connect(self.changestate_ident2maxval)
    
    # ident2 inc
    self.lineEdit_ident2inc = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident2inc.setSizePolicy(sizePolicy)
    self.lineEdit_ident2inc.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident2inc.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident2inc.setObjectName("lineEdit_ident2inc")
    self.lineEdit_ident2inc.setMaxLength(8)
    val = df.loc[65,"VALUE"]
    self.lineEdit_ident2inc.setText(str(val))
    self.lineEdit_ident2inc.setDisabled(True)
    self.horizontalLayout_24.addWidget(self.lineEdit_ident2inc)
    self.lineEdit_ident2inc.setToolTip("increment value for ident2")
    self.lineEdit_ident2inc.setStyleSheet(tipstyle) 
    self.lineEdit_ident2inc.textChanged[str].connect(self.changestate_ident2inc)
    
    spacerItem_ident2 = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_24.addItem(spacerItem_ident2)
  
    self.verticalLayout_12.addLayout(self.horizontalLayout_24)
    
    
    self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_25.setObjectName("horizontalLayout_25")
    self.label_25 = QtWidgets.QLabel(self.groupBox_range)
    self.label_25.setObjectName("label_25")
    self.label_25.setStyleSheet(labelstyle)
    self.label_25.setText("Ident3:")       
    self.horizontalLayout_25.addWidget(self.label_25)
       
    self.lineEdit_ident3 = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident3.setSizePolicy(sizePolicy)
    self.lineEdit_ident3.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident3.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident3.setObjectName("lineEdit_ident3")
    self.lineEdit_ident3.setMaxLength(6)
    val = df.loc[54,"VALUE"]
    self.lineEdit_ident3.setText(str(val))
    self.lineEdit_ident3.setDisabled(True)
    self.horizontalLayout_25.addWidget(self.lineEdit_ident3)
    self.lineEdit_ident3.setToolTip("tertiary ident to use for skeleton input ranging")
    self.lineEdit_ident3.setStyleSheet(tipstyle) 
    self.lineEdit_ident3.textChanged[str].connect(self.changestate_ident3)
    
    # ident3 minval
    self.lineEdit_ident3minval = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident3minval.setSizePolicy(sizePolicy)
    self.lineEdit_ident3minval.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident3minval.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident3minval.setObjectName("lineEdit_ident3minval")
    self.lineEdit_ident3minval.setMaxLength(8)
    val = df.loc[59,"VALUE"]
    self.lineEdit_ident3minval.setText(str(val))
    self.lineEdit_ident3minval.setDisabled(True)
    self.horizontalLayout_25.addWidget(self.lineEdit_ident3minval)
    self.lineEdit_ident3minval.setToolTip("minimum value for ident3")
    self.lineEdit_ident3minval.setStyleSheet(tipstyle) 
    self.lineEdit_ident3minval.textChanged[str].connect(self.changestate_ident3minval)
    
    # ident3 maxval
    self.lineEdit_ident3maxval = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident3maxval.setSizePolicy(sizePolicy)
    self.lineEdit_ident3maxval.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident3maxval.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident3maxval.setObjectName("lineEdit_ident3maxval")
    self.lineEdit_ident3maxval.setMaxLength(8)
    val = df.loc[60,"VALUE"]
    self.lineEdit_ident3maxval.setText(str(val))
    self.lineEdit_ident3maxval.setDisabled(True)
    self.horizontalLayout_25.addWidget(self.lineEdit_ident3maxval)
    self.lineEdit_ident3maxval.setToolTip("maximum value for ident3")
    self.lineEdit_ident3maxval.setStyleSheet(tipstyle) 
    self.lineEdit_ident3maxval.textChanged[str].connect(self.changestate_ident3maxval)   
    
    # ident3 inc
    self.lineEdit_ident3inc = QtWidgets.QLineEdit(self.groupBox_range)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_ident3inc.setSizePolicy(sizePolicy)
    self.lineEdit_ident3inc.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_ident3inc.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_ident3inc.setObjectName("lineEdit_ident3inc")
    self.lineEdit_ident3inc.setMaxLength(8)
    val = df.loc[66,"VALUE"]
    self.lineEdit_ident3inc.setText(str(val))
    self.lineEdit_ident3inc.setDisabled(True)
    self.horizontalLayout_25.addWidget(self.lineEdit_ident3inc)
    self.lineEdit_ident3inc.setToolTip("increment value for ident3")
    self.lineEdit_ident3inc.setStyleSheet(tipstyle) 
    self.lineEdit_ident3inc.textChanged[str].connect(self.changestate_ident3inc)  
    
    spacerItem_ident3 = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_25.addItem(spacerItem_ident3)
  
    self.verticalLayout_12.addLayout(self.horizontalLayout_25)
    
    self.verticalLayout_7.addWidget(self.groupBox_range)
    
    Wizard.setPage(8,self.wizardPage8)