# -*- coding: utf-8 -*-
"""
Created on Tue Mar 30 12:01:38 2021

@author: Christopher.Willacy
"""
from PyQt5 import QtCore, QtGui, QtWidgets


#----------------------------------------------------------------------
#  SETUP PAGE
#----------------------------------------------------------------------
def PageSetup(self,Wizard,icons,tipstyle,groupstyle,storage):
        
    self.wizardPage2 = QtWidgets.QWizardPage()
    self.wizardPage2.setSubTitle("")
    self.wizardPage2.setObjectName("wizardPage2")
    self.wizardPage2.setTitle('Workflow Setup')
    self.gridLayout_2 = QtWidgets.QGridLayout(self.wizardPage2)
    self.gridLayout_2.setObjectName("gridLayout_2")
    self.groupBox_2 = QtWidgets.QGroupBox(self.wizardPage2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
    self.groupBox_2.setSizePolicy(sizePolicy)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_2.setFont(font)
    self.groupBox_2.setStyleSheet(groupstyle)
    self.groupBox_2.setObjectName("groupBox_2")
    self.groupBox_2.setTitle("Workflow Options")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
    self.verticalLayout.setObjectName("verticalLayout")
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.label_3 = QtWidgets.QLabel(self.groupBox_2)
    self.label_3.setObjectName("label_3")
    self.label_3.setText("Aquisition Type:")
    self.horizontalLayout_2.addWidget(self.label_3)
    self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
    self.comboBox.setSizePolicy(sizePolicy)
    self.comboBox.setCurrentText("")
    self.comboBox.setObjectName("comboBox")
    self.comboBox.setFixedWidth(135)      
    self.horizontalLayout_2.addWidget(self.comboBox)
    self.comboBox.addItem("OBN")
    #self.comboBox.addItem("Streamer")
    #self.comboBox.addItem("Land")        
    self.comboBox.setToolTip("select type of workflow to build")
    self.comboBox.setStyleSheet(tipstyle)
    spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_2.addItem(spacerItem)
    self.verticalLayout.addLayout(self.horizontalLayout_2)
    
    self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_8.setObjectName("horizontalLayout_8")
    self.comboBox.activated[str].connect(self.changestate_workflow)
    self.label_9 = QtWidgets.QLabel(self.groupBox_2)
    self.label_9.setObjectName("label_9")
    self.label_9.setText("Source Type:")
    self.horizontalLayout_8.addWidget(self.label_9)
    self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
    self.comboBox_2.setSizePolicy(sizePolicy)
    self.comboBox_2.setCurrentText("")
    self.comboBox_2.setObjectName("comboBox_2")
    self.comboBox_2.setFixedWidth(135)
 
    self.horizontalLayout_8.addWidget(self.comboBox_2)
    self.comboBox_2.addItem("Single")
    self.comboBox_2.addItem("Mixed")
    self.comboBox_2.setToolTip("select if the survey contains different source types")
    self.comboBox_2.setStyleSheet(tipstyle)
    spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
    self.horizontalLayout_8.addItem(spacerItem1)
    self.verticalLayout.addLayout(self.horizontalLayout_8)
    #------------     
    self.horizontalLayout_splitident = QtWidgets.QHBoxLayout()
    self.horizontalLayout_splitident.setObjectName("horizontalLayout_splitident")
    #self.horizontalLayout_2c.addItem(spacerItem)
    self.verticalLayout.addLayout(self.horizontalLayout_splitident)
    
    self.horizontalLayout_splitident2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_splitident2.setObjectName("horizontalLayout_splitident2")
    
    self.label_splitident = QtWidgets.QLabel(self.groupBox_2)
    self.label_splitident.setObjectName("label_splitident")
    self.label_splitident.setText("Source split ident:")
    self.lineEdit_splitident = QtWidgets.QLineEdit(self.groupBox_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_splitident.sizePolicy().hasHeightForWidth())
    self.lineEdit_splitident.setSizePolicy(sizePolicy)
    self.lineEdit_splitident.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_splitident.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_splitident.setObjectName("lineEdit_splitident")
    self.lineEdit_splitident.setMaxLength(6)
    self.lineEdit_splitident.setText("")
    self.lineEdit_splitident.setDisabled(True)
    self.lineEdit_splitident.setToolTip("enter the shot code corresponding to the low-frequency source")
    self.lineEdit_splitident.setStyleSheet(tipstyle)
    self.horizontalLayout_splitident2.addWidget(self.label_splitident)
    self.horizontalLayout_splitident2.addWidget(self.lineEdit_splitident)
    spacerItem_splitident = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_splitident2.addItem(spacerItem_splitident)
    self.verticalLayout.addLayout(self.horizontalLayout_splitident2)

    self.lineEdit_splitident.textChanged[str].connect(self.changestate_splitident)
    
    #------------
    self.horizontalLayout_2c = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2c.setObjectName("horizontalLayout_2c")
    #self.horizontalLayout_2c.addItem(spacerItem)
    self.verticalLayout.addLayout(self.horizontalLayout_2c)
    
    self.horizontalLayout_8c = QtWidgets.QHBoxLayout()
    self.horizontalLayout_8c.setObjectName("horizontalLayout_8c")
    
    self.label_9c = QtWidgets.QLabel(self.groupBox_2)
    self.label_9c.setObjectName("label_9c")
    self.label_9c.setText("Source split value:")
    self.lineEdit_shtcod = QtWidgets.QLineEdit(self.groupBox_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_shtcod.sizePolicy().hasHeightForWidth())
    self.lineEdit_shtcod.setSizePolicy(sizePolicy)
    self.lineEdit_shtcod.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_shtcod.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_shtcod.setObjectName("lineEdit_shtcod")
    self.lineEdit_shtcod.setMaxLength(6)
    self.lineEdit_shtcod.setText("")
    self.lineEdit_shtcod.setDisabled(True)
    self.lineEdit_shtcod.setToolTip("enter the shot code corresponding to the low-frequency source")
    self.lineEdit_shtcod.setStyleSheet(tipstyle)
    self.horizontalLayout_8c.addWidget(self.label_9c)
    self.horizontalLayout_8c.addWidget(self.lineEdit_shtcod)
    spacerItem_shtcod = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_8c.addItem(spacerItem_shtcod)
    
    #self.horizontalLayout_8c.addItem(spacerItem1)
    self.verticalLayout.addLayout(self.horizontalLayout_8c)

    self.comboBox_2.activated[str].connect(self.changestate_srctype)
    self.lineEdit_shtcod.textChanged[str].connect(self.changestate_shtcod) 

    #-------------
    self.horizontalLayout_reident = QtWidgets.QHBoxLayout()
    self.horizontalLayout_reident.setObjectName("horizontalLayout_reident")
    self.label_reident = QtWidgets.QLabel(self.groupBox_2)
    self.label_reident.setObjectName("label_reident")
    self.label_reident.setText("Re-Ident:")
    self.horizontalLayout_reident.addWidget(self.label_reident)
    self.checkBox_reident = QtWidgets.QCheckBox(self.groupBox_2)
    self.checkBox_reident.setText("")
    self.checkBox_reident.setChecked(False)
    self.checkBox_reident.setObjectName("checkBox_reident")
    self.horizontalLayout_reident.addWidget(self.checkBox_reident)
    self.checkBox_reident.setToolTip("re-calculate the key survey idents")
    self.checkBox_reident.setStyleSheet(tipstyle)
    self.verticalLayout.addLayout(self.horizontalLayout_reident)
    self.checkBox_reident.clicked.connect(self.changestate_reident)
        
    #-------------
    self.horizontalLayout_dev = QtWidgets.QHBoxLayout()
    self.horizontalLayout_dev.setObjectName("horizontalLayout_dev")
    self.label_dev = QtWidgets.QLabel(self.groupBox_2)
    self.label_dev.setObjectName("label_dev")
    self.label_dev.setText("Use development library:")
    self.horizontalLayout_dev.addWidget(self.label_dev)
    self.checkBox_dev = QtWidgets.QCheckBox(self.groupBox_2)
    self.checkBox_dev.setText("")
    self.checkBox_dev.setChecked(False)
    self.checkBox_dev.setObjectName("checkBox_dev")
    self.horizontalLayout_dev.addWidget(self.checkBox_dev)
    self.checkBox_dev.setToolTip("build with the development version of AcqLib")
    self.checkBox_dev.setStyleSheet(tipstyle)
    self.verticalLayout.addLayout(self.horizontalLayout_dev)
    self.checkBox_dev.clicked.connect(self.changestate_dev)
    
    #-------------
    
    self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
    self.groupBox = QtWidgets.QGroupBox(self.wizardPage2)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox.setFont(font)
    self.groupBox.setStyleSheet(groupstyle)
    self.groupBox.setObjectName("groupBox")
    self.groupBox.setTitle("Skeleton Details")
    self.verticalLayout_skl = QtWidgets.QVBoxLayout(self.groupBox)
    self.verticalLayout_skl.setObjectName("verticalLayout_skl")    
    
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.label_2 = QtWidgets.QLabel(self.groupBox)
    self.label_2.setObjectName("label_2")
    self.label_2.setText("JobPro Revision Number: ")
    self.horizontalLayout.addWidget(self.label_2)
    self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit.setSizePolicy(sizePolicy)
    self.lineEdit.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit.setObjectName("lineEdit")
    self.lineEdit.setMaxLength(6)
    self.lineEdit.setText("000.00")
    self.lineEdit.setToolTip("enter a jobpro revision number to use")
    self.lineEdit.setStyleSheet(tipstyle)
    self.lineEdit.textChanged[str].connect(self.changestate_jobrev) 
    self.horizontalLayout.addWidget(self.lineEdit)
    spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout.addItem(spacerItem2)
    
    self.verticalLayout_skl.addLayout(self.horizontalLayout)
    
    self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
    
    #-----------
                 
    self.horizontalLayout_pool = QtWidgets.QHBoxLayout()
    self.horizontalLayout_pool.setObjectName("horizontalLayout_pool")

    self.label_pool = QtWidgets.QLabel(self.groupBox)
    self.label_pool.setObjectName("label_pool")
    self.label_pool.setText("Data Pool:")
    self.horizontalLayout_pool.addWidget(self.label_pool)
    self.comboBox_pool = QtWidgets.QComboBox(self.groupBox)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboBox_pool.sizePolicy().hasHeightForWidth())
    self.comboBox_pool.setSizePolicy(sizePolicy)
    self.comboBox_pool.setCurrentText("")
    self.comboBox_pool.setObjectName("comboBox_pool")
    self.comboBox_pool.setFixedWidth(135) 
    self.horizontalLayout_pool.addWidget(self.comboBox_pool)
       
        
    for element in storage:
        self.comboBox_pool.addItem(element)
    
    self.comboBox_pool.setToolTip("jobpro data pool to use for workflow run")
    self.comboBox_pool.setStyleSheet(tipstyle)
    self.comboBox_pool.activated[str].connect(self.changestate_pool)
    spacerItem_pool = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
    self.horizontalLayout_pool.addItem(spacerItem_pool)
    self.verticalLayout_skl.addLayout(self.horizontalLayout_pool)
    
    Wizard.setPage(2,self.wizardPage2)     