# -*- coding: utf-8 -*-
"""
Created on Tue Mar 30 13:29:37 2021

@author: Christopher.Willacy
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

#----------------------------------------------------------------------
#   OUTPUT OPTIONS
#----------------------------------------------------------------------
def PageOutput(self,Wizard,icons,df,tipstyle,groupstyle): 
    
    self.wizardPage8 = QtWidgets.QWizardPage()
    self.wizardPage8.setObjectName("wizardPage8")
    self.wizardPage8.setTitle("Output Options")
    self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.wizardPage8)
    self.verticalLayout_7.setObjectName("verticalLayout_7")
    self.groupBox_6 = QtWidgets.QGroupBox(self.wizardPage8)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
    self.groupBox_6.setSizePolicy(sizePolicy)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_6.setFont(font)
    self.groupBox_6.setStyleSheet(groupstyle)
    self.groupBox_6.setObjectName("groupBox_6")
    self.groupBox_6.setTitle("Location")
    self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
    self.verticalLayout_8.setObjectName("verticalLayout_8")
    self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_6.setObjectName("horizontalLayout_6")
    self.label_7 = QtWidgets.QLabel(self.groupBox_6)
    self.label_7.setObjectName("label_7")
    self.label_7.setText("Output skl directory:")  
    self.label_7.setFixedWidth(200)      
    self.horizontalLayout_6.addWidget(self.label_7)
    self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_6)
    self.lineEdit_4.setObjectName("lineEdit_4")
    self.horizontalLayout_6.addWidget(self.lineEdit_4)
    self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_6)
    self.pushButton_2.setObjectName("pushButton_2")
    self.pushButton_2.setStyleSheet("border: none")
    self.pushButton_2.setIcon(QIcon(icons[3]))
    self.horizontalLayout_6.addWidget(self.pushButton_2)
    self.verticalLayout_8.addLayout(self.horizontalLayout_6)
    
    self.horizontalLayout_filename = QtWidgets.QHBoxLayout()
    self.horizontalLayout_filename.setObjectName("horizontalLayout_filename")
    self.label_filename = QtWidgets.QLabel(self.groupBox_6)
    self.label_filename.setObjectName("label_filename")
    self.label_filename.setText("Wizard filename:")  
    self.label_filename.setFixedWidth(200)      
    self.horizontalLayout_filename.addWidget(self.label_filename)
    self.lineEdit_filename = QtWidgets.QLineEdit(self.groupBox_6)
    self.lineEdit_filename.setObjectName("lineEdit_filename")
    self.lineEdit_filename.textChanged[str].connect(self.changestate_filename)
    
    filename = str(df.loc[51,"VALUE"])
    
    if filename != '':
        self.lineEdit_filename.setText(filename)      
    else:
        defname = str(df.loc[3,"VALUE"]) + "-simwiz"
        self.lineEdit_filename.setText(defname)
    
    self.horizontalLayout_filename.addWidget(self.lineEdit_filename)
    
    spacerItem_filename = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_filename.addItem(spacerItem_filename)
    
    self.verticalLayout_8.addLayout(self.horizontalLayout_filename)
    
    self.lineEdit_4.setToolTip("output directory where the skeletons will be written")
    self.lineEdit_4.setStyleSheet(tipstyle) 
    self.lineEdit_4.setText('')
    self.lineEdit_4.textChanged[str].connect(self.changestate_outdir)
    self.verticalLayout_7.addWidget(self.groupBox_6)
    self.groupBox_9 = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_9.setFont(font)
    self.groupBox_9.setStyleSheet(groupstyle)
    self.groupBox_9.setObjectName("groupBox_9")
    self.groupBox_9.setTitle("SSF Output")    
    self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_9)
    self.verticalLayout_11.setObjectName("verticalLayout_11")
    self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_7.setObjectName("horizontalLayout_7")
    self.label_8 = QtWidgets.QLabel(self.groupBox_9)
    self.label_8.setObjectName("label_8")
    self.label_8.setText("Generate SSF traces?:")       
    self.horizontalLayout_7.addWidget(self.label_8)
    self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_9)
    self.checkBox_3.setText("")
    self.checkBox_3.setChecked(True)
    self.checkBox_3.setObjectName("checkBox_3")
    self.horizontalLayout_7.addWidget(self.checkBox_3)
    self.verticalLayout_11.addLayout(self.horizontalLayout_7)
    self.checkBox_3.setToolTip("option to generate SSF traces on output (default=true)")
    self.checkBox_3.setStyleSheet(tipstyle) 
    self.checkBox_3.clicked.connect(self.changestate_ssf)
    self.verticalLayout_7.addWidget(self.groupBox_9)
    
    
    
    self.groupBox_8 = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_8.setFont(font)
    self.groupBox_8.setStyleSheet(groupstyle)
    self.groupBox_8.setObjectName("groupBox_8")
    self.groupBox_8.setTitle("QC Displays")       
    self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_8)
    self.verticalLayout_10.setObjectName("verticalLayout_10")
    self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_17.setObjectName("horizontalLayout_17")
    self.label_18 = QtWidgets.QLabel(self.groupBox_8)
    self.label_18.setObjectName("label_18")
    self.label_18.setText("Geometry displays?")      
    self.horizontalLayout_17.addWidget(self.label_18)
    self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_8)
    self.checkBox_6.setText("")
    self.checkBox_6.setChecked(False)
    self.checkBox_6.setObjectName("checkBox_6")
    self.horizontalLayout_17.addWidget(self.checkBox_6)
    self.checkBox_6.setToolTip("option to create source/receiver geometry qc images")
    self.checkBox_6.setStyleSheet(tipstyle) 
    self.checkBox_6.clicked.connect(self.changestate_qcgeom)
    self.verticalLayout_10.addLayout(self.horizontalLayout_17)
    
    self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_19.setObjectName("horizontalLayout_19")
    self.label_19 = QtWidgets.QLabel(self.groupBox_8)
    self.label_19.setObjectName("label_19")
    self.label_19.setText("Timing displays?")        
    self.horizontalLayout_19.addWidget(self.label_19)
    self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_8)
    self.checkBox_7.setText("")
    self.checkBox_7.setChecked(False)
    self.checkBox_7.setObjectName("checkBox_7")
    self.horizontalLayout_19.addWidget(self.checkBox_7)
    self.checkBox_7.setToolTip("option to create source timing qc images")
    self.checkBox_7.setStyleSheet(tipstyle) 
    self.checkBox_7.clicked.connect(self.changestate_qctime)
    self.verticalLayout_10.addLayout(self.horizontalLayout_19)
    
    self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_20.setObjectName("horizontalLayout_20")
    self.label_20 = QtWidgets.QLabel(self.groupBox_8)
    self.label_20.setObjectName("label_20")
    self.label_20.setText("Sensor depth displays?")       
    self.horizontalLayout_20.addWidget(self.label_20)
    self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_8)
    self.checkBox_8.setText("")
    self.checkBox_8.setChecked(False)
    self.checkBox_8.setObjectName("checkBox_8")
    self.horizontalLayout_20.addWidget(self.checkBox_8)
    self.checkBox_8.setToolTip("option to create sensor depth qc images")
    self.checkBox_8.setStyleSheet(tipstyle) 
    self.checkBox_8.clicked.connect(self.changestate_qcdepth)
    self.verticalLayout_10.addLayout(self.horizontalLayout_20)
    self.verticalLayout_7.addWidget(self.groupBox_8)
    
    #--------

    self.groupBox_perf = QtWidgets.QGroupBox(self.wizardPage8)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_perf.setFont(font)
    self.groupBox_perf.setStyleSheet(groupstyle)
    self.groupBox_perf.setObjectName("groupBox_perf")
    self.groupBox_perf.setTitle("Sort Size")        
    self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_perf)
    self.verticalLayout_11.setObjectName("verticalLayout_11")
    self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_21.setObjectName("horizontalLayout_21")
    self.label_21 = QtWidgets.QLabel(self.groupBox_perf)
    self.label_21.setObjectName("label_21")
    self.label_21.setText("SQSORT maxrec:")       
    self.horizontalLayout_21.addWidget(self.label_21)
    
    self.lineEdit_sqsaf = QtWidgets.QLineEdit(self.groupBox_perf)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_sqsaf.setSizePolicy(sizePolicy)
    self.lineEdit_sqsaf.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_sqsaf.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_sqsaf.setObjectName("lineEdit_sqsaf")
    self.lineEdit_sqsaf.setMaxLength(7)
    val = df.loc[32,"VALUE"]
    self.lineEdit_sqsaf.setText(str(val))
    self.horizontalLayout_21.addWidget(self.lineEdit_sqsaf)
    self.lineEdit_sqsaf.setToolTip("maximum number of SAF records that need to be stored in memory expressed in millions")
    self.lineEdit_sqsaf.setStyleSheet(tipstyle) 
    self.lineEdit_sqsaf.textChanged[str].connect(self.changestate_sqsaf)
    
    spacerItem_sqsaf = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_21.addItem(spacerItem_sqsaf)
    
    self.verticalLayout_11.addLayout(self.horizontalLayout_21)
    
    self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_22.setObjectName("horizontalLayout_22")
    self.label_22 = QtWidgets.QLabel(self.groupBox_perf)
    self.label_22.setObjectName("label_22")
    self.label_22.setText("SRTALL maxsize:")
    self.horizontalLayout_22.addWidget(self.label_22)
    
    self.lineEdit_srtall = QtWidgets.QLineEdit(self.groupBox_perf)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
    self.lineEdit_srtall.setSizePolicy(sizePolicy)
    self.lineEdit_srtall.setMaximumSize(QtCore.QSize(75, 16777215))
    self.lineEdit_srtall.setBaseSize(QtCore.QSize(0, 0))
    self.lineEdit_srtall.setObjectName("lineEdit_sqsaf")
    self.lineEdit_srtall.setMaxLength(6)
    val = df.loc[33,"VALUE"]
    self.lineEdit_srtall.setText(str(val))
    self.lineEdit_srtall.setText("4000")
    self.horizontalLayout_22.addWidget(self.lineEdit_srtall)
    self.lineEdit_srtall.setToolTip("maximum size of the sort buffer in Mb's")
    self.lineEdit_srtall.setStyleSheet(tipstyle)
    self.lineEdit_srtall.textChanged[str].connect(self.changestate_srtall)
    spacerItem_srtall = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)        
    self.horizontalLayout_22.addItem(spacerItem_srtall)
    
    self.verticalLayout_11.addLayout(self.horizontalLayout_22)                    
    self.verticalLayout_7.addWidget(self.groupBox_perf)

    Wizard.setPage(8,self.wizardPage8)