# -*- coding: utf-8 -*-
"""
Created on Tue Mar 30 13:18:52 2021

@author: Christopher.Willacy
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

#----------------------------------------------------------------------
#  GEOMETRY PAGE
#----------------------------------------------------------------------
def PageGeom(self,Wizard,icons,tipstyle,groupstyle,labelstyle):  

    self.wizardPage4 = QtWidgets.QWizardPage()
    self.wizardPage4.setObjectName("wizardPage4")
    self.wizardPage4.setTitle("Geometry Build")
    self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wizardPage4)
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.groupBox_5 = QtWidgets.QGroupBox(self.wizardPage4)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_5.setFont(font)
    self.groupBox_5.setStyleSheet(groupstyle)
    self.groupBox_5.setObjectName("groupBox_5")
    self.groupBox_5.setTitle("Advanced Options")
    self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
    self.verticalLayout_6.setObjectName("verticalLayout_6")
    self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3.setObjectName("horizontalLayout_3")
    self.label_4 = QtWidgets.QLabel(self.groupBox_5)
    self.label_4.setObjectName("label_4")
    self.label_4.setStyleSheet(labelstyle)
    self.label_4.setText("Create mirror geometry?:")
    self.horizontalLayout_3.addWidget(self.label_4)
    self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
    self.checkBox.setText("")
    self.checkBox.setChecked(False)
    self.checkBox.setObjectName("checkBox")        
    self.horizontalLayout_3.addWidget(self.checkBox)
    self.checkBox.setToolTip("option to create a mirror geometry")
    self.checkBox.setStyleSheet(tipstyle)       
    self.verticalLayout_6.addLayout(self.horizontalLayout_3)
    self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4.setObjectName("horizontalLayout_4")
    self.label_5 = QtWidgets.QLabel(self.groupBox_5)
    self.label_5.setObjectName("label_5")
    self.label_5.setStyleSheet(labelstyle)
    self.label_5.setText("Mirror depth shift:")       
    self.horizontalLayout_4.addWidget(self.label_5)
    self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
    self.lineEdit_3.setSizePolicy(sizePolicy)
    self.lineEdit_3.setObjectName("lineEdit_3")
    self.lineEdit_3.setDisabled(True)
    #self.lineEdit_3.setFixedWidth(50)
    self.horizontalLayout_4.addWidget(self.lineEdit_3)
    self.lineEdit_3.setToolTip("vertical shift to apply to create the mirrored region")
    self.lineEdit_3.setStyleSheet(tipstyle)  
    self.lineEdit_3.textChanged[str].connect(self.changestate_mirrz) 
    spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_4.addItem(spacerItem5)
    self.verticalLayout_6.addLayout(self.horizontalLayout_4)
    self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5.setObjectName("horizontalLayout_5")
    self.label_6 = QtWidgets.QLabel(self.groupBox_5)
    self.label_6.setObjectName("label_6")
    self.label_6.setStyleSheet(labelstyle)
    self.label_6.setText("Apply reciprocity?:")
    self.horizontalLayout_5.addWidget(self.label_6)
    self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
    self.checkBox_2.setText("")
    self.checkBox_2.setChecked(True)
    self.checkBox_2.setObjectName("checkBox_2")
    self.horizontalLayout_5.addWidget(self.checkBox_2)
    self.checkBox_2.setToolTip("option to create a reciprocal geometry (default for OBN)")
    self.checkBox_2.setStyleSheet(tipstyle)   
    self.checkBox_2.clicked.connect(self.changestate_recip)
    self.verticalLayout_6.addLayout(self.horizontalLayout_5)
    self.verticalLayout_5.addWidget(self.groupBox_5)
 
    
    #----next box----
    self.groupBox_7 = QtWidgets.QGroupBox(self.wizardPage4)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_7.setFont(font)
    self.groupBox_7.setStyleSheet(groupstyle)
    self.groupBox_7.setObjectName("groupBox_7")
    self.groupBox_7.setTitle("Sensor Depths")
    self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_7)
    self.verticalLayout_9.setObjectName("verticalLayout_9")
    self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_15.setObjectName("horizontalLayout_15")
    self.label_16 = QtWidgets.QLabel(self.groupBox_7)
    self.label_16.setObjectName("label_16")
    self.label_16.setStyleSheet(labelstyle)
    self.label_16.setText("Interpolate node depths?:")
    self.horizontalLayout_15.addWidget(self.label_16)
    self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_7)
    self.checkBox_5.setText("")
    self.checkBox_5.setChecked(False)
    self.checkBox_5.setObjectName("checkBox_5")
    self.checkBox_5.setChecked(False)
    self.horizontalLayout_15.addWidget(self.checkBox_5)
    self.checkBox_5.setToolTip("option to update the node depths by interpolation from a horizon")
    self.checkBox_5.setStyleSheet(tipstyle)       
    self.verticalLayout_9.addLayout(self.horizontalLayout_15)
    self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_16.setObjectName("horizontalLayout_16")
    self.label_17 = QtWidgets.QLabel(self.groupBox_7)
    self.label_17.setBaseSize(QtCore.QSize(0, 0))
    self.label_17.setObjectName("label_17")
    self.label_17.setStyleSheet(labelstyle)
    self.label_17.setText("Horizon SAF:")
    self.horizontalLayout_16.addWidget(self.label_17)
    self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
    self.lineEdit_10.setObjectName("lineEdit_10")
    self.lineEdit_10.setDisabled(True)
    self.horizontalLayout_16.addWidget(self.lineEdit_10)
    self.lineEdit_10.setToolTip("SAF horizon file to use for node depth interpolation")
    self.lineEdit_10.setStyleSheet(tipstyle)       
    self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_7)
    self.pushButton_6.setObjectName("pushButton_6")
    self.pushButton_6.setStyleSheet("border: none")
    self.horizontalLayout_16.addWidget(self.pushButton_6)
    self.pushButton_6.setDisabled(True)        
    self.verticalLayout_9.addLayout(self.horizontalLayout_16)
    self.verticalLayout_5.addWidget(self.groupBox_7)
    self.pushButton_6.setIcon(QIcon(icons[3]))    
    self.checkBox.clicked.connect(self.changestate_mirr)
    self.checkBox_5.clicked.connect(self.changestate_interp)
    self.lineEdit_10.textChanged[str].connect(self.changestate_wbsaf) 
    #Wizard.addPage(self.wizardPage4)
    Wizard.setPage(4,self.wizardPage4)        