# -*- coding: utf-8 -*-
"""
Created on Tue Mar 30 13:23:29 2021

@author: Christopher.Willacy
"""
from PyQt5 import QtGui, QtWidgets


#----------------------------------------------------------------------
#  BLEND
#----------------------------------------------------------------------
def PageBlend(self,Wizard,icons,df,tipstyle,groupstyle,labelstyle):   
    self.wizardPage_blend = QtWidgets.QWizardPage()
    self.wizardPage_blend.setObjectName("wizardPage6")
    self.wizardPage_blend.setTitle("Post-Modelling Data Blending")
    self.verticalLayout_blend = QtWidgets.QVBoxLayout(self.wizardPage_blend)
    self.verticalLayout_blend.setObjectName("verticalLayout_blend")
    self.groupBox_blend = QtWidgets.QGroupBox(self.wizardPage_blend)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.groupBox_blend.sizePolicy().hasHeightForWidth())
    self.groupBox_blend.setSizePolicy(sizePolicy)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.groupBox_blend.setFont(font)
    self.groupBox_blend.setStyleSheet(groupstyle)
    self.groupBox_blend.setObjectName("groupBox_blend")
    self.groupBox_blend.setTitle("Blending Options")
    self.verticalLayout_blend.addWidget(self.groupBox_blend)
    self.verticalLayout_blend2 = QtWidgets.QVBoxLayout(self.groupBox_blend)
    self.verticalLayout_blend2.setObjectName("verticalLayout_blend2")
    
    self.horizontalLayout_blend = QtWidgets.QHBoxLayout()
    self.horizontalLayout_blend.setObjectName("horizontalLayout_blend")
    self.label_tmax = QtWidgets.QLabel(self.groupBox_blend)
    self.label_tmax.setObjectName("label_tmax")
    self.label_tmax.setStyleSheet(labelstyle)
    self.label_tmax.setText("Input data trace length:")       
    self.horizontalLayout_blend.addWidget(self.label_tmax)
    self.lineEdit_tmax = QtWidgets.QLineEdit(self.groupBox_blend)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_tmax.sizePolicy().hasHeightForWidth())
    self.lineEdit_tmax.setSizePolicy(sizePolicy)
    self.lineEdit_tmax.setObjectName("lineEdit_tmax")
    self.lineEdit_tmax.setMaxLength(10)
    self.horizontalLayout_blend.addWidget(self.lineEdit_tmax)       
    self.verticalLayout_blend2.addLayout(self.horizontalLayout_blend)       
    self.lineEdit_tmax.setToolTip("trace length for the modelled data in ms")
    self.lineEdit_tmax.setStyleSheet(tipstyle)
    self.lineEdit_tmax.editingFinished.connect(self.changestate_tmax)

    #self.lineEdit_tmax.textChanged[str].connect(self.changestate_tmax)
    spacerItem_tmax = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    self.horizontalLayout_blend.addItem(spacerItem_tmax)
    
    self.horizontalLayout_dt = QtWidgets.QHBoxLayout()
    self.horizontalLayout_dt.setObjectName("horizontalLayout_dt")
    self.label_dt = QtWidgets.QLabel(self.groupBox_blend)
    self.label_dt.setObjectName("label_dt")
    self.label_dt.setStyleSheet(labelstyle)
    self.label_dt.setText("Input data sample interval:")
    self.horizontalLayout_dt.addWidget(self.label_dt)
    self.lineEdit_dt = QtWidgets.QLineEdit(self.groupBox_blend)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_dt.sizePolicy().hasHeightForWidth())
    self.lineEdit_dt.setSizePolicy(sizePolicy)
    self.lineEdit_dt.setObjectName("lineEdit_tout")
    self.lineEdit_dt.setMaxLength(10)
    self.horizontalLayout_dt.addWidget(self.lineEdit_dt)       
    self.verticalLayout_blend2.addLayout(self.horizontalLayout_dt)       
    self.lineEdit_dt.setToolTip("sample interval for the modelled data in ms")
    self.lineEdit_dt.setStyleSheet(tipstyle)
    self.lineEdit_dt.textChanged[str].connect(self.changestate_dt)
    spacerItem_dt1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    self.horizontalLayout_dt.addItem(spacerItem_dt1)  
    
    self.horizontalLayout_tout = QtWidgets.QHBoxLayout()
    self.horizontalLayout_tout.setObjectName("horizontalLayout_tout")
    self.label_tout = QtWidgets.QLabel(self.groupBox_blend)
    self.label_tout.setObjectName("label_tout")
    self.label_tout.setStyleSheet(labelstyle)
    self.label_tout.setText("Output data trace length:")
    self.horizontalLayout_tout.addWidget(self.label_tout)
    self.lineEdit_tout = QtWidgets.QLineEdit(self.groupBox_blend)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_tout.sizePolicy().hasHeightForWidth())
    self.lineEdit_tout.setSizePolicy(sizePolicy)
    self.lineEdit_tout.setObjectName("lineEdit_tout")
    self.lineEdit_tout.setMaxLength(10)
    self.horizontalLayout_tout.addWidget(self.lineEdit_tout)       
    self.verticalLayout_blend2.addLayout(self.horizontalLayout_tout)       
    self.lineEdit_tout.setToolTip("trace length for the output data in ms. must be a multiple of 1000ms.")
    self.lineEdit_tout.setStyleSheet(tipstyle)
    self.lineEdit_tout.textChanged[str].connect(self.changestate_tout)
    spacerItem_tout = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    self.horizontalLayout_tout.addItem(spacerItem_tout)  
    
    self.horizontalLayout_t0 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_t0.setObjectName("horizontalLayout_t0")
    self.label_t0 = QtWidgets.QLabel(self.groupBox_blend)
    self.label_t0.setObjectName("label_t0")
    self.label_t0.setStyleSheet(labelstyle)
    self.label_t0.setText("Start time of wavelet:")
    self.horizontalLayout_t0.addWidget(self.label_t0)
    self.lineEdit_t0 = QtWidgets.QLineEdit(self.groupBox_blend)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEdit_t0.sizePolicy().hasHeightForWidth())
    self.lineEdit_t0.setSizePolicy(sizePolicy)
    self.lineEdit_t0.setObjectName("lineEdit_t0")
    self.lineEdit_t0.setMaxLength(10)
    self.horizontalLayout_t0.addWidget(self.lineEdit_t0)       
    self.verticalLayout_blend2.addLayout(self.horizontalLayout_t0)       
    self.lineEdit_t0.setToolTip("start time in ms for the wavelet")
    self.lineEdit_t0.setStyleSheet(tipstyle)
    val = df.loc[26,"VALUE"]
    self.lineEdit_t0.setText(str(val))
    self.lineEdit_t0.textChanged[str].connect(self.changestate_t0)
    spacerItem_t0 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    self.horizontalLayout_t0.addItem(spacerItem_t0) 
    
    Wizard.setPage(6,self.wizardPage_blend)